"""Deterministic infrastructure insight bank used by DemoProvider.

Each entry is a complete, validated engineering insight. The provider
selects by topic/category and never calls the network.
"""

from __future__ import annotations

INSIGHTS: list[dict] = [
    {
        "title": "Give production roles verbs, not kingdoms",
        "topic": "IAM least privilege for production roles",
        "category": "AWS",
        "summary": "Production breakages and breaches both start with IAM roles that can do everything in an account. Split identities by job, constrain resources with conditions, and treat wildcard actions as an incident, not a convenience.",
        "real_world_scenario": "A deploy role used by GitHub Actions can create, delete, and read every resource in the account. A compromised fine-grained token then empties an S3 data lake because the same role that ships a Lambda also has s3:*.",
        "technical_explanation": "AWS IAM evaluates identity policies, resource policies, SCPs, and permission boundaries together. Least privilege is not a single Deny; it is a narrow Allow plus a permission boundary that the pipeline cannot widen. Use condition keys such as aws:SourceIp, aws:PrincipalOrgID, aws:RequestedRegion, and aws:ResourceTag to bind a role to a workload. Prefer aws:CalledVia and iam:PassedToService when a role must pass another role. Access Analyzer and CloudTrail Management events show unused actions you can delete after a soak period.",
        "architecture": "Org management account holds SCPs. Workload accounts receive a deploy role, a runtime role, and a break-glass role. CI authenticates with GitHub OIDC, assumes the deploy role, and passes only the runtime role to compute. Permission boundaries cap both roles. CloudTrail, Access Analyzer, and IAM Access Advisor feed a weekly unused-permission report.",
        "best_practices": [
            "Separate deploy-time and runtime identities; never reuse them.",
            "Put a permission boundary on every pipeline-assumable role.",
            "Require OIDC federation instead of long-lived access keys.",
            "Tag resources and condition on those tags in IAM policies.",
        ],
        "practical_recommendation": "This week, list every IAM role assumed by CI. Split any role that both deploys infrastructure and runs the application. Attach a permission boundary that forbids iam:CreateRole without a boundary and forbids s3:DeleteObject on data-classified buckets.",
        "common_mistakes": [
            "Granting AdministratorAccess to unblock a pipeline and leaving it there.",
            "Putting secrets in GitHub repository variables instead of using OIDC.",
            "Using inline wildcards on Resource because the ARN is not known yet.",
        ],
        "what_to_learn_next": [
            "IAM Access Analyzer custom policy checks in CI.",
            "SCP patterns that deny leaving the home region.",
            "Permission boundaries versus SCPs and when to use both.",
        ],
        "tags": ["aws", "iam", "least-privilege", "oidc", "security"],
    },
    {
        "title": "Public access blocks are a control, not a suggestion",
        "topic": "S3 bucket encryption and public access blocks",
        "category": "AWS",
        "summary": "S3 data incidents are rarely exotic. They are buckets created without account-level Block Public Access, default encryption, or Object Ownership. Set those three controls at the account, then prove them with Access Analyzer.",
        "real_world_scenario": "A new analytics bucket is created from a console click during an incident. ACLs remain enabled, a teammate adds a public-read ACL for a 'quick share', and a customer export becomes world-readable for six hours before GuardDuty fires.",
        "technical_explanation": "S3 Block Public Access can be set on the account and on each bucket. Account-level BPA rejects new public ACLs and policies even if a bucket policy is later edited. Default encryption with SSE-KMS and a customer-managed key gives you CloudTrail key usage and the ability to revoke access by disabling the key. Bucket owner enforced Object Ownership disables ACLs so writers cannot grant public-read independently of the bucket policy. Access Analyzer for S3 reports remaining public or shared findings.",
        "architecture": "Account BPA on. CloudFormation/Terraform module creates buckets with BPA, SSE-KMS, versioning, and Object Ownership BucketOwnerEnforced. A central logging bucket receives access logs. EventBridge rules on PutBucketAcl and PutBucketPolicy notify the security channel. Macie optionally classifies objects in data accounts.",
        "best_practices": [
            "Enable Block Public Access at the account before creating buckets.",
            "Use SSE-KMS CMKs for classified data, not only SSE-S3.",
            "Turn on Object Ownership BucketOwnerEnforced and disable ACLs.",
            "Version objects and apply a lifecycle that still preserves delete markers.",
        ],
        "practical_recommendation": "Turn on S3 Block Public Access for the entire AWS account today, then run Access Analyzer. Any remaining public bucket should have an owner, a ticket, and a removal date, not a comment that says 'needed for demo'.",
        "common_mistakes": [
            "Relying on a bucket name being secret.",
            "Using ACL public-read for static websites instead of CloudFront OAC.",
            "Encrypting with SSE-S3 and assuming that equals access control.",
        ],
        "what_to_learn_next": [
            "CloudFront Origin Access Control to S3.",
            "S3 Object Lock in compliance mode for backups.",
            "Macie sensitive-data discovery jobs.",
        ],
        "tags": ["aws", "s3", "encryption", "public-access", "kms"],
    },
    {
        "title": "Private by default, NAT as an exception",
        "topic": "VPC design with private subnets and NAT",
        "category": "AWS",
        "summary": "A VPC that puts application runtimes in public subnets will eventually expose something you did not intend. Keep compute private, egress through NAT or VPC endpoints, and treat internet-facing load balancers as the only public network objects.",
        "real_world_scenario": "An ECS service is launched into a public subnet so it can pull images. A security group later opens 22/tcp from 0.0.0.0/0 for debugging. The task public IP is scanned within minutes.",
        "technical_explanation": "Public subnets have a default route to an Internet Gateway. Private subnets route 0.0.0.0/0 to a NAT gateway or have no internet route at all. VPC endpoints (Gateway for S3/DynamoDB, Interface for AWS APIs) remove the need for NAT for AWS service traffic and keep that traffic on the Amazon network. Split at least two AZs, isolate public ALB subnets from private app subnets, and use network ACLs only as a coarse subnet guard, not as your primary control. Security groups should be referenced by ID, not by wide CIDRs.",
        "architecture": "Two public subnets for load balancers only. Two or more private app subnets. Two private data subnets with no NAT route. Interface endpoints for ECR, Logs, Secrets Manager, and STS. Gateway endpoints for S3. NAT gateways per AZ for remaining egress. Flow Logs to S3 or CloudWatch.",
        "best_practices": [
            "Never assign public IPs to application tasks or instances.",
            "Prefer VPC endpoints over NAT for AWS API traffic.",
            "Place NAT gateways in each AZ you run to avoid cross-AZ hairpins.",
            "Capture VPC Flow Logs before you need them in an incident.",
        ],
        "practical_recommendation": "Inventory every ENI with a public IP. If it is not a load balancer, NAT gateway, or bastion with SSM, move the workload to a private subnet this sprint and add the missing VPC endpoints.",
        "common_mistakes": [
            "One giant /16 subnet because 'CIDR planning is hard'.",
            "A single NAT gateway for three AZs, creating a hidden AZ dependency.",
            "Using 0.0.0.0/0 in security groups 'just for now'.",
        ],
        "what_to_learn_next": [
            "PrivateLink to expose internal APIs without VPC peering meshes.",
            "IPv6 egress-only internet gateways.",
            "Network Firewall or Gateway Load Balancer inspection patterns.",
        ],
        "tags": ["aws", "vpc", "networking", "nat", "endpoints"],
    },
    {
        "title": "Private Endpoints beat service firewalls",
        "topic": "Azure Private Endpoints for PaaS services",
        "category": "Azure",
        "summary": "Public PaaS endpoints with IP firewalls still live on the public internet. Private Endpoints plus disabling public network access keep Key Vault, Storage, and SQL on your VNet, which is what most regulated designs actually require.",
        "real_world_scenario": "A storage account allows public access from 'selected networks' and a developer VPN IP. The allow list drifts, a partner IP is added, and a SAS URL leaked in logs becomes reachable from the internet.",
        "technical_explanation": "A Private Endpoint is a NIC in your VNet with a private IP that maps to a PaaS resource via Private Link. DNS must resolve the resource FQDN to that private IP, usually through a private DNS zone linked to the VNet (for example privatelink.blob.core.windows.net). If public network access remains enabled, clients can still bypass the Private Endpoint. Pair Private Endpoints with 'disable public network access', private DNS, and a hub-and-spoke so spokes share the zones. NSGs on the subnet control NIC traffic; they do not replace Private Link.",
        "architecture": "Hub VNet hosts shared private DNS zones and optionally Azure Firewall. Spokes host workload subnets and Private Endpoints, or a dedicated private-endpoint subnet. Traffic to Azure SQL, Storage, and Key Vault never uses public IPs. Azure Policy denies new public PaaS endpoints.",
        "best_practices": [
            "Disable public network access after the Private Endpoint works.",
            "Centralize private DNS zones in the hub and link every spoke.",
            "Use Azure Policy to audit and deny public PaaS exposure.",
            "Put Private Endpoints in a dedicated subnet to simplify NSGs.",
        ],
        "practical_recommendation": "Pick one production Key Vault still on a public endpoint. Create a Private Endpoint, link the privatelink vault DNS zone, disable public access, and confirm the app still resolves and authenticates from the VNet.",
        "common_mistakes": [
            "Creating a Private Endpoint but leaving public access enabled.",
            "Forgetting private DNS, so clients still resolve to public IPs.",
            "Peering every spoke to every other spoke instead of using a hub.",
        ],
        "what_to_learn_next": [
            "Azure Private Link service for your own APIs.",
            "Azure Policy initiative for private-only PaaS.",
            "Private DNS Resolver for hybrid DNS.",
        ],
        "tags": ["azure", "private-link", "networking", "dns", "paas"],
    },
    {
        "title": "Policy should stop the bad deploy, not file a ticket after it",
        "topic": "Azure Policy as preventative guardrails",
        "category": "Azure",
        "summary": "Audit-only Azure Policy is a report. Deny and DeployIfNotExists are controls. Put the few rules that actually prevent data loss and public exposure into Deny at management-group scope, then let teams request exemptions with an expiry.",
        "real_world_scenario": "A subscription has 40 Audit policies and zero Deny policies. A contributor creates a storage account with public blob access. The weekly compliance email arrives four days after the account is already in use.",
        "technical_explanation": "Azure Policy evaluates ARM properties during PUT/PATCH. Deny effects block non-compliant resources at Resource Manager. DeployIfNotExists can add diagnostic settings or private DNS links, but it needs a managed identity and can lag. Policy assignments at the management group apply to all child subscriptions. Exemptions should be time-boxed and tied to a change ticket. Combine Policy with RBAC: Policy constrains resource shape, RBAC constrains who may create resources.",
        "architecture": "Tenant root management group assigns a small Deny initiative: no public storage, required HTTPS, required tags, allowed locations. Platform MG adds DeployIfNotExists for Activity Log and Defender. Workload MGs add environment-specific audits. Exemptions expire in 30 days unless renewed.",
        "best_practices": [
            "Use Deny for a short list of non-negotiables, not for every preference.",
            "Assign initiatives at management group scope, not per subscription by hand.",
            "Give every exemption an owner and an expiry date.",
            "Test new Deny policies in Audit first on a canary subscription.",
        ],
        "practical_recommendation": "Promote three Audit policies to Deny this month: allowed locations, deny storage public blob access, and require HTTPS on App Service. Watch the Activity Log for blocked deployments and fix the platform modules that still emit non-compliant templates.",
        "common_mistakes": [
            "Hundreds of Audit policies and no Deny, then claiming the platform is governed.",
            "Permanent exemptions copied from the first blocked deploy.",
            "Assigning Policy at subscription scope and drifting between teams.",
        ],
        "what_to_learn_next": [
            "Azure Policy guest configuration for OS settings.",
            "EPAC (Enterprise Policy as Code) for versioned assignments.",
            "Resource Graph queries for exemption hygiene.",
        ],
        "tags": ["azure", "policy", "governance", "guardrails", "arm"],
    },
    {
        "title": "One identity plane, many clouds",
        "topic": "Multi-cloud identity federation",
        "category": "Cloud Infrastructure",
        "summary": "Multi-cloud fails first at identity. Humans and pipelines should federate from one IdP into AWS IAM roles and Azure Entra apps. Long-lived access keys in two clouds is not a multi-cloud strategy; it is two breach surfaces.",
        "real_world_scenario": "AWS uses IAM users with access keys in a password manager. Azure uses named user accounts with owner on subscriptions. A contractor leaves and still has an AWS key because offboarding only disabled the Entra user.",
        "technical_explanation": "SAML or OIDC federation maps an IdP group to a cloud role. In AWS, IAM Identity Center (or a SAML provider) issues short-lived credentials into permission sets. In Azure, Entra ID is already the control plane; app registrations and federated credentials replace client secrets for workloads. For GitHub Actions, OIDC tokens are exchanged for cloud credentials with audience and subject conditions bound to a repository and environment. Humans never receive standing admin. Break-glass accounts are offline, monitored, and rare.",
        "architecture": "Corporate IdP is the source of groups. AWS IAM Identity Center permission sets map those groups. Azure PIM elevates Entra roles just in time. CI uses OIDC to AWS roles and Azure federated credentials. Access reviews run every 90 days. CloudTrail and Entra sign-in logs land in the same SIEM.",
        "best_practices": [
            "Eliminate IAM users and Azure client secrets for humans and CI.",
            "Bind OIDC trust to repository, environment, and branch.",
            "Use just-in-time elevation for administrative roles.",
            "Automate joiner-mover-leaver from the HR/IdP source of truth.",
        ],
        "practical_recommendation": "Pick the most privileged AWS access key still in CI. Replace it with GitHub OIDC and an IAM role whose trust policy allows only that repository and production environment. Rotate and delete the key the same day.",
        "common_mistakes": [
            "Copying AWS access keys into Azure Key Vault and calling it federation.",
            "Trusting any GitHub org subject in the OIDC role policy.",
            "Leaving break-glass credentials in the same IdP as everyday users with no extra monitoring.",
        ],
        "what_to_learn_next": [
            "AWS IAM Identity Center permission set design.",
            "Entra ID PIM and access reviews.",
            "SPIFFE/SPIRE for workload identity across runtimes.",
        ],
        "tags": ["identity", "oidc", "aws", "azure", "federation"],
    },
    {
        "title": "Certificates expire in production, not in calendars",
        "topic": "DNS, TLS, and certificate rotation",
        "category": "Networking",
        "summary": "Most TLS outages are operational, not cryptographic. Automate issuance, put expiry on a dashboard with a page-worthy SLO, and make DNS changes a reviewed pipeline, not a console click during an incident.",
        "real_world_scenario": "A wildcard certificate issued 13 months ago expires at 00:01 UTC on a holiday. The load balancer still serves the old cert. Mobile clients fail while the web team argues about who owns Route 53.",
        "technical_explanation": "TLS depends on a valid chain, the correct SANs, and clients that can reach a trusted CA. ACM, Azure App Service certificates, or cert-manager can issue and attach certificates, but only if DNS-01 or HTTP-01 validation still works. Certificate transparency and expiry exporters (for example blackbox or a dedicated cert check) should alert at 30, 14, and 7 days. DNS TTLs should be low enough for cutover but not so low that you DDoS your own nameservers. CAA records restrict which CAs may issue for the zone.",
        "architecture": "Public DNS in a dedicated account or subscription. Certificates issued by ACM or cert-manager into the load balancer or ingress. Monitoring probes check TLS expiry and chain. Changes to records go through Terraform or a DNS pipeline with dual review. CAA and DNSSEC enabled where the registrar supports them.",
        "best_practices": [
            "Alert on certificate expiry from an external probe, not from tribal knowledge.",
            "Keep DNS in infrastructure as code with a documented rollback.",
            "Set CAA records so only your intended CA can issue.",
            "Rehearse a certificate replacement the same way you rehearse failover.",
        ],
        "practical_recommendation": "Export every certificate attached to a production listener. If any expire inside 30 days without an automated renewal path, fix that path before writing more features.",
        "common_mistakes": [
            "Manual PFX uploads with no calendar and no owner.",
            "Pointing a CNAME at a vendor and forgetting their certificate SAN.",
            "Lowering TTL during an incident for the first time.",
        ],
        "what_to_learn_next": [
            "ACM private CA versus public certs.",
            "cert-manager DNS-01 with Route 53 or Azure DNS.",
            "mTLS between internal services.",
        ],
        "tags": ["dns", "tls", "certificates", "networking", "reliability"],
    },
    {
        "title": "Segment first, then talk about zero trust",
        "topic": "Zero-trust network segmentation",
        "category": "Networking",
        "summary": "Zero trust is not a product you buy. It is identity-aware access plus network paths that do not exist by default. Start by removing flat east-west connectivity between environments, then put a policy engine in front of human access.",
        "real_world_scenario": "Prod, staging, and a contractor jump box share one /16. Ransomware on a developer VM can ARP-scan the payment database because the security group allows RFC1918 to RFC1918 on 5432.",
        "technical_explanation": "Segmentation can be implemented with subnets and route tables, security groups / NSGs, firewalls, service meshes, and identity-aware proxies. The useful order is: (1) no route between prod data and developer networks, (2) allow lists by security group ID not CIDR, (3) human access through SSM or a ZTNA product instead of a standing VPN full-tunnel, (4) workload identity for service-to-service calls. Microsegmentation tools fail when the underlying network is still a single broadcast-adjacent soup.",
        "architecture": "Separate VPCs/VNets per environment. Hub firewall inspects north-south. East-west between prod app and prod data is SG/NSG referenced, not open CIDR. Engineers use SSM Session Manager or an identity-aware proxy. Service identity uses IAM roles or workload identity, not shared network trust.",
        "best_practices": [
            "Default-deny between environments; peer or link only with a ticket.",
            "Replace VPN-as-home-network with per-application access.",
            "Prefer instance/service identity over IP allow lists.",
            "Log accepted and rejected flows for the sensitive subnets.",
        ],
        "practical_recommendation": "Draw the current path from a laptop to production data. If that path is 'VPN then any private IP', insert SSM or ZTNA and remove the database port from the VPN security group this week.",
        "common_mistakes": [
            "Buying a zero-trust vendor while leaving 10.0.0.0/8 allowed in prod SGs.",
            "A single shared 'internal' security group used by every service.",
            "Assuming private IP equals trusted IP.",
        ],
        "what_to_learn_next": [
            "AWS SSM Session Manager and VPC endpoints for SSM.",
            "Azure Bastion versus ZTNA.",
            "Service mesh authorization policies as a second layer.",
        ],
        "tags": ["zero-trust", "segmentation", "nsg", "security-groups", "ztna"],
    },
    {
        "title": "systemd is your control plane on the box",
        "topic": "Linux systemd service hardening",
        "category": "Linux",
        "summary": "A Linux service that still runs as root with a writable working directory is a gift to whoever finds the next RCE. Use systemd directives to drop privileges, lock the filesystem, and make the unit fail closed.",
        "real_world_scenario": "A Python worker started from rc.local as root writes logs next to its code. A path traversal in an upload handler overwrites the worker file. Persistence is a one-line change and nobody notices because the process name stayed the same.",
        "technical_explanation": "systemd unit files can set User, Group, NoNewPrivileges, PrivateTmp, ProtectSystem, ProtectHome, ProtectKernelTunables, CapabilityBoundingSet, RestrictAddressFamilies, SystemCallFilter, and MemoryMax. Combined, they create a service-specific sandbox without a container runtime. Socket-activated services can wait until traffic arrives. Restart=on-failure with StartLimitBurst prevents crash loops from hammering the disk. EnvironmentFile should not hold secrets; use a credentials directory or a vault agent.",
        "architecture": "Immutable base image or golden AMI. Application installed as a dedicated user. Unit file in /etc/systemd/system with hardening directives and a drop-in for environment-specific limits. Logs to journald, forwarded to the central collector. Configuration management or an image pipeline owns the unit, not SSH edits.",
        "best_practices": [
            "Run every long-lived process as a dedicated non-root user.",
            "Set ProtectSystem=strict and give the service a writable StateDirectory.",
            "Use systemd credentials or a vault, never plaintext Environment=SECRET.",
            "Cap memory and tasks so one leak cannot take the host.",
        ],
        "practical_recommendation": "Open the unit file for your most privileged Linux daemon. Add NoNewPrivileges=true, ProtectSystem=strict, PrivateTmp=true, and a non-root User. Restart it in staging and fix the paths that were accidentally relying on /root.",
        "common_mistakes": [
            "Leaving RemainAfterExit services running as root from a leftover init script.",
            "chmod 777 on a working directory because the app could not write logs.",
            "Putting secrets in the unit file committed to git.",
        ],
        "what_to_learn_next": [
            "systemd sandboxing directives in depth.",
            "SELinux or AppArmor profiles for the same binary.",
            "ssh-less operations with cloud-init and SSM.",
        ],
        "tags": ["linux", "systemd", "hardening", "least-privilege", "hosts"],
    },
    {
        "title": "Patch windows are a product, not a hope",
        "topic": "Windows Server patch windows and WSUS",
        "category": "Windows Server",
        "summary": "Unpatched Windows Server is still a leading ransomware path. Define maintenance windows, stage patches, require reboot ownership, and measure compliance. WSUS or a cloud update ring only works if someone owns the exception list.",
        "real_world_scenario": "A file server missed three Patch Tuesdays because 'the app team could not reboot'. A public exploit lands, RDP is reachable from a jump host that shares credentials, and the backup admin share is encrypted before anyone notices.",
        "technical_explanation": "WSUS or Windows Update for Business rings control which updates are approved and when they are offered. Group Policy or Intune sets automatic download and scheduled install. The hard part is reboot: Cluster-Aware Updating, rolling updates for IIS farms, and a documented freeze calendar. Defender signatures and OS patches are different pipelines; both need SLAs. Inventory (MECM, Intune, or SSM Inventory) must tell you which hosts are outside the ring.",
        "architecture": "WSUS in the datacenter or Update rings in Intune/MECM. Pilot OU/ring gets patches in 48 hours. Broad production follows after a soak. Clusters roll automatically. Isolated hosts use a dedicated update path. Compliance dashboard pages if a severity-critical patch is missing after the SLA.",
        "best_practices": [
            "Give every server a named reboot owner and a window.",
            "Pilot patches on a representative slice before fleet-wide approval.",
            "Track missing KBs as an SLO, not as a monthly spreadsheet.",
            "Separate 'cannot reboot' into an architecture problem, not a permanent exception.",
        ],
        "practical_recommendation": "List Windows hosts that have not rebooted in 60 days. For each one, either schedule a rolling update or move the workload to a pattern that can restart (farm, cluster, or immutable image).",
        "common_mistakes": [
            "Approving updates in WSUS and never checking whether hosts installed them.",
            "Disabling Windows Update to 'stabilize production'.",
            "RDP exposed to the VPN with local admin passwords that never rotate.",
        ],
        "what_to_learn_next": [
            "Cluster-Aware Updating.",
            "Immutable Windows images versus patch-in-place.",
            "LAPS / Windows LAPS for local admin rotation.",
        ],
        "tags": ["windows", "patching", "wsus", "ransomware", "operations"],
    },
    {
        "title": "Promote artifacts, not hope",
        "topic": "GitOps promotion between environments",
        "category": "DevOps",
        "summary": "If staging and production are deployed by different pipelines from different commits, you do not have promotion; you have two lottery tickets. Build once, store an immutable artifact, and promote the same digest.",
        "real_world_scenario": "Prod is deployed by merging to main, which rebuilds the image. Staging was a feature branch image from yesterday. A library CVE exists only in the prod rebuild because the lockfile drifted during the second docker build.",
        "technical_explanation": "GitOps promotion means the artifact (container digest, AMI ID, Terraform plan artifact) is immutable and referenced by environment manifests. Argo CD or Flux watches a prod overlay that points at the same digest staging already ran. Application config can change per environment; the binary should not. Provenance (SLSA, attestations) binds the digest to a commit SHA. Promotion PRs are small: they change a tag or digest pin, not application source.",
        "architecture": "CI builds and signs an image on merge to main. Staging GitOps overlay is updated automatically. After soak and tests, a promotion PR updates the production overlay to the same digest. CD controllers reconcile. Rollback is a Git revert to the previous digest.",
        "best_practices": [
            "Build once; promote by digest, never by moving a mutable latest tag.",
            "Keep environment differences in config, not in rebuilt binaries.",
            "Sign artifacts and verify signatures in the cluster or account.",
            "Make rollback a Git operation you have rehearsed.",
        ],
        "practical_recommendation": "Find any production deploy job that runs docker build. Stop it. Point production at the image digest already running in staging, and make the next release a promotion PR.",
        "common_mistakes": [
            "Using latest tags in production manifests.",
            "Rebuilding on each environment 'to pick up env-specific ARG values'.",
            "Manual kubectl apply in prod that GitOps immediately overwrites, or worse, that GitOps never sees.",
        ],
        "what_to_learn_next": [
            "SLSA provenance and Cosign signatures.",
            "Argo CD ApplicationSets for many clusters.",
            "Progressive delivery with analysis (canary/flagger).",
        ],
        "tags": ["gitops", "devops", "promotion", "supply-chain", "cd"],
    },
    {
        "title": "State is the production database of Terraform",
        "topic": "Terraform state locking and remote backends",
        "category": "Terraform",
        "summary": "Local terraform.tfstate on a laptop is an unbacked production database. Use a remote backend with locking, restrict who can read state (it contains secrets), and never run apply from two places without a lock.",
        "real_world_scenario": "Two engineers apply the same stack. One creates a database, the other destroys and recreates it because state diverged. The application loses an unbacked volume. There is no lock and no state history.",
        "technical_explanation": "Terraform maps resources to state. Without a remote backend, that map lives on disk. S3 + DynamoDB, Terraform Cloud, Azure Storage with leases, or GCS with native locking serialize applies. State can contain plaintext secrets from resource attributes; treat the backend as sensitive. Use state encryption, bucket policies, and least-privilege CI roles. Workspaces or separate state files per environment prevent a staging apply from touching prod. Imports and moved blocks exist so you do not destroy to rename.",
        "architecture": "One state per environment per component. S3 backend with bucket versioning, SSE-KMS, and DynamoDB lock table (or equivalent). CI role can read/write only that prefix. Engineers plan locally against the remote state but apply through CI. Broken state is recovered from versioning, not from guesswork.",
        "best_practices": [
            "Remote backend with locking on every non-throwaway stack.",
            "Version the state store and test a restore once.",
            "Split blast radius with separate states, not one mega-state.",
            "Apply only in CI for production.",
        ],
        "practical_recommendation": "If any production stack still uses local state, migrate it to a locked remote backend today using terraform init -migrate-state, then delete the local copies from laptops and chat threads.",
        "common_mistakes": [
            "Checking terraform.tfstate into Git.",
            "One state file for all environments.",
            "Running terraform apply during an incident from a laptop with an old state snapshot.",
        ],
        "what_to_learn_next": [
            "Terraform import and moved blocks.",
            "Policy as code with Sentinel or OPA on plans.",
            "Terragrunt or stacks for DRY backends without a mega-module.",
        ],
        "tags": ["terraform", "state", "iac", "locking", "s3"],
    },
    {
        "title": "Your runtime should not include a package manager",
        "topic": "Docker image provenance and distroless runtimes",
        "category": "Docker",
        "summary": "Fat images slow deploys and expand CVE noise. Build in a full SDK image, copy a static binary or a minimal runtime into distroless or a scratch-based image, and pin by digest so you know what actually ran.",
        "real_world_scenario": "A Node service ships ubuntu:latest plus apt-get build tools. A scanner reports 400 CVEs. Nobody can tell which matter because the runtime includes compilers, shells, and leftover credentials from docker build.",
        "technical_explanation": "Multi-stage Dockerfiles keep compilers in a builder stage and copy only the artifact to a runtime stage. Distroless and similar images omit shells and package managers, which removes a class of container breakout convenience. Pin base images by digest, not by floating tags. Generate an SBOM at build and attach it to the digest. Do not bake secrets into layers; use runtime injection. Run as a non-root USER and make the filesystem read-only where the app allows it.",
        "architecture": "CI builds a multi-stage image, scans it, signs it, and pushes digest tags. Runtime clusters pull by digest. Admission policy rejects images without a signature or with a shell if your standard forbids it. Secrets come from the platform, not from ENV in the Dockerfile.",
        "best_practices": [
            "Use multi-stage builds and a minimal runtime image.",
            "Pin FROM lines by digest.",
            "Produce an SBOM and sign the digest.",
            "Run as non-root with a read-only root filesystem when possible.",
        ],
        "practical_recommendation": "Take your noisiest production image, convert it to multi-stage with a distroless or slim runtime, pin the digest, and compare CVE counts and image size before and after. Use that diff to set the new standard.",
        "common_mistakes": [
            "COPY . . then running npm install in the same layer as the app in production.",
            "Leaving curl and a shell in the runtime 'for debugging'.",
            "Using latest tags on FROM and in Kubernetes manifests.",
        ],
        "what_to_learn_next": [
            "BuildKit cache mounts and reproducible builds.",
            "Cosign and admission controllers.",
            "Chainguard or distroless base image migration.",
        ],
        "tags": ["docker", "supply-chain", "distroless", "sbom", "containers"],
    },
    {
        "title": "Rollouts fail closed when PDBs are lies",
        "topic": "Kubernetes PodDisruptionBudgets and rollouts",
        "category": "Kubernetes",
        "summary": "PodDisruptionBudgets protect availability only if replica counts can satisfy them. A PDB of minAvailable=1 with replicas=1 blocks nodes forever, or a missing PDB lets a drain take the last pod. Match PDBs to how you actually roll.",
        "real_world_scenario": "A cluster upgrade drains a node. A singleton pod with minAvailable=1 cannot leave. The drain hangs for hours, or an operator deletes the PDB and the pod dies with the node. Either way, the service has no honest availability policy.",
        "technical_explanation": "A PDB limits voluntary disruptions (drains, evictions). It does not save you from node failure. Deployments, StatefulSets, and Jobs interact differently with PDBs. For a Deployment, replicas must be high enough that maxUnavailable or minAvailable still leaves a serving pod. RollingUpdate maxUnavailable and maxSurge must be compatible with the PDB or the rollout stalls. Readiness probes must be true only when the process can take traffic, or you will pass the PDB and still black-hole requests. Disruption budgets should be tested with kubectl drain in staging.",
        "architecture": "Each customer-facing Deployment has replicas >= 2 across zones, a PDB, Pod anti-affinity or topology spread, and a rollout strategy that never drops below the PDB. Cluster upgrades use surge nodes or drain with timeouts and alerts. HPA and PDB are reviewed together so scale-to-zero is explicit, not accidental.",
        "best_practices": [
            "Never set minAvailable equal to replicas unless you accept blocked drains.",
            "Run at least two replicas in production for anything with a PDB.",
            "Test drains in staging as part of the cluster upgrade rehearsal.",
            "Make readiness probes match real dependency health.",
        ],
        "practical_recommendation": "For every Deployment with replicas=1 in production, either add a second replica and a PDB or document it as a singleton with a named owner and a restore path. Then try a drain in staging.",
        "common_mistakes": [
            "Copy-pasting minAvailable: 1 onto every service.",
            "maxUnavailable: 50% on a two-replica deployment, dropping to one then zero during a bad rollout.",
            "Using liveness probes as readiness probes and killing pods during dependency blips.",
        ],
        "what_to_learn_next": [
            "topologySpreadConstraints versus pod anti-affinity.",
            "Argo Rollouts or Flagger for analysis-driven rollouts.",
            "Priority and preemption during node pressure.",
        ],
        "tags": ["kubernetes", "pdb", "rollouts", "availability", "drain"],
    },
    {
        "title": "CI should assume a role, not own a key",
        "topic": "GitHub Actions OIDC to cloud roles",
        "category": "CI/CD",
        "summary": "Long-lived cloud keys in GitHub secrets are standing credentials in a chat-adjacent store. GitHub's OIDC token can be exchanged for AWS or Azure credentials that exist only for that job, repository, and environment.",
        "real_world_scenario": "A repository secret AWS_SECRET_ACCESS_KEY is copied into three workflows, including a fork-enabled pull_request workflow. A contributor submits a PR that prints env and exfiltrates the key.",
        "technical_explanation": "GitHub Actions can request an OIDC token with an audience and a subject that includes repo, ref, and environment. AWS IAM roles trust token.actions.githubusercontent.com with a condition on sub. Azure federated credentials match the same claims on an app registration. Permissions on the job must include id-token: write. Pull requests from forks should not get production environment secrets or production federated roles. Environments add protection rules and reviewers for production.",
        "architecture": "Each GitHub environment maps to one cloud role with a tight trust policy. Build jobs use a read-only role. Deploy jobs use a deploy role only after environment reviewers. No long-lived access keys in GitHub. CloudTrail shows the GitHub repo in the session identity.",
        "best_practices": [
            "Use OIDC with subject conditions bound to repo and environment.",
            "Never expose production roles to pull_request from forks.",
            "Keep id-token: write only on jobs that need it.",
            "Prefer environment protection rules over repository-wide secrets.",
        ],
        "practical_recommendation": "Create an IAM role or Azure federated credential for one production deploy workflow. Switch that workflow to OIDC, confirm a successful deploy, then delete the static key from GitHub and from IAM.",
        "common_mistakes": [
            "Trusting repo:* in the IAM condition because the first token failed.",
            "Printing OIDC tokens or cloud credentials in debug logs.",
            "Using pull_request_target with write credentials.",
        ],
        "what_to_learn_next": [
            "GitHub environment protection rules.",
            "AWS IAM condition keys for OIDC.",
            "SLSA and workflow pinning (actions by SHA).",
        ],
        "tags": ["github-actions", "oidc", "cicd", "aws", "azure"],
    },
    {
        "title": "Alert on user pain, not on CPU folklore",
        "topic": "SLO-based alerting instead of noisy thresholds",
        "category": "Monitoring",
        "summary": "CPU at 80% is not an incident. Error budget burn is. Define SLIs that match user journeys, set SLOs, and page on fast burn. Everything else is a ticket or a dashboard.",
        "real_world_scenario": "On-call gets 40 pages a night from CPU, memory, and disk watermarks. The one real outage is a 5xx spike that nobody notices because the channel is already noise. The team starts ignoring PagerDuty.",
        "technical_explanation": "An SLI is a quantitative measure of user success (availability, latency at a quantile, freshness). An SLO is a target over a window. Error budget is 1 - SLO. Multi-window multi-burn-rate alerts fire when the budget is consuming too fast (page) or consistently (ticket). Thresholds on saturation are still useful as diagnostic symptoms, not as pages. High cardinality labels make burn-rate queries expensive; keep SLI metrics cheap and stable.",
        "architecture": "RED or USE metrics on the edge (ingress, load balancer, or synthetic). Recording rules compute burn rates for 5m/1h and 30m/6h windows. Alertmanager or equivalent routes fast-burn to pager and slow-burn to a ticket. Dashboards show symptoms (CPU, saturation) next to the SLI, not instead of it.",
        "best_practices": [
            "Page on error-budget burn, not on raw CPU.",
            "Use at least two burn windows to catch both spikes and slow leaks.",
            "Keep SLI metrics low-cardinality and user-centric.",
            "Review noisy alerts weekly and delete them.",
        ],
        "practical_recommendation": "Pick one customer-facing endpoint. Define availability as the ratio of successful non-4xx-client requests. Set a 99.9% monthly SLO. Replace the CPU page with a 2% hourly burn-rate page and see if on-call gets quieter and faster.",
        "common_mistakes": [
            "Paging on every 5xx without excluding client-cancelled requests.",
            "Hundreds of Grafana alerts copied from a template.",
            "SLOs set at 100% so every error is theoretically a breach.",
        ],
        "what_to_learn_next": [
            "Google SRE workbook multi-window burn rates.",
            "Synthetics versus real-user SLIs.",
            "Error budget policies that actually freeze releases.",
        ],
        "tags": ["slo", "monitoring", "alerting", "sre", "error-budget"],
    },
    {
        "title": "Traces are how distributed systems confess",
        "topic": "Distributed tracing across service boundaries",
        "category": "Observability",
        "summary": "Logs without a trace id are anecdotes. Propagate W3C trace context across HTTP, queues, and workflows so a single request can be reconstructed when latency or errors cross team boundaries.",
        "real_world_scenario": "Checkout is slow. Each service owner shows a healthy p99 on their dashboard. The time is spent in retries between two services that do not share a request id, so nobody can prove where the 2.4 seconds went.",
        "technical_explanation": "OpenTelemetry SDKs create spans and inject traceparent (and optionally baggage) into outbound calls. Sampling can be head-based or tail-based; production needs a strategy that keeps error traces. Queues must carry the context in message attributes or you break the graph at the broker. A backend such as Tempo, Honeycomb, X-Ray, or Jaeger stores spans. Correlate logs by injecting trace_id into the log record. Metrics can exemplify to traces so an SLO breach opens a trace, not a guessing session.",
        "architecture": "Each service uses the OTel SDK or auto-instrumentation. A collector receives OTLP, applies tail sampling, and exports to the store. Ingress starts the trace. Async workers extract context from message headers. Frontends show trace ids on error pages for support.",
        "best_practices": [
            "Propagate W3C traceparent on every hop, including queues.",
            "Sample enough error traces to be useful; do not only sample 1% of successes.",
            "Put trace_id in logs.",
            "Start traces at the edge, not inside a random microservice.",
        ],
        "practical_recommendation": "Take one user-facing request that crosses two services. Confirm a single trace id appears in both logs and in your tracing UI. If it does not, fix context propagation before adding more dashboards.",
        "common_mistakes": [
            "Creating a new trace in every service, destroying parent-child relationships.",
            "Logging PII in span attributes.",
            "Turning on 100% tracing in production without a budget and then disabling it after the bill.",
        ],
        "what_to_learn_next": [
            "Tail-based sampling in the OpenTelemetry collector.",
            "Trace exemplars on Prometheus histograms.",
            "Queue instrumentation for SQS, Service Bus, or Kafka.",
        ],
        "tags": ["observability", "tracing", "opentelemetry", "sre", "latency"],
    },
    {
        "title": "Secrets that cannot rotate are incidents waiting",
        "topic": "Secrets management and rotation",
        "category": "Cloud Security",
        "summary": "A secret that lives in a repo, an AMI, or a Slack thread cannot be rotated without a scavenger hunt. Put credentials in a manager, inject at runtime, and rehearse rotation. Static keys in environment files are a backlog of breaches.",
        "real_world_scenario": "A database password is in a .env file baked into an AMI. The password leaks through a support bundle. Changing it requires a new AMI, a deploy, and six forgotten lambdas that still have the old value in console environment variables.",
        "technical_explanation": "AWS Secrets Manager, SSM Parameter Store, Azure Key Vault, and similar systems store secrets, encrypt them with KMS, and emit rotation events. Applications should fetch at startup or using a sidecar, with caching and failure modes that do not log the secret. IAM or managed identities replace embedding the secret-to-get-the-secret. Rotation needs two valid versions during cutover (dual-write or dual-read) or you will break clients. Git history is not a rotation tool; leaked secrets in Git need invalidation, not deletion of a file.",
        "architecture": "Runtime roles read a named secret. Rotation Lambda or Key Vault rotation policy updates the engine and the secret version. Deployments never contain secret values. CI uses OIDC and short-lived tokens. Pre-commit and CI scanners block new secrets in Git.",
        "best_practices": [
            "Inject secrets at runtime via a manager and workload identity.",
            "Rehearse rotation for the database password and the TLS client cert.",
            "Scan Git and container images for secrets continuously.",
            "Prefer short-lived credentials over rotatable static passwords when the platform allows it.",
        ],
        "practical_recommendation": "Choose one production static password. Move it into Secrets Manager or Key Vault, grant only the runtime role GetSecretValue, update the app to read it, then rotate the password and watch the app survive.",
        "common_mistakes": [
            "Base64-encoding a secret in Kubernetes YAML and calling it encryption.",
            "Logging configuration objects that include the secret.",
            "Rotating the secret in the manager but not in the leftover console env vars.",
        ],
        "what_to_learn_next": [
            "AWS Secrets Manager rotation runbooks.",
            "External Secrets Operator versus CSI drivers.",
            "Workload identity for Kubernetes and Lambda.",
        ],
        "tags": ["secrets", "kms", "rotation", "security", "iam"],
    },
    {
        "title": "Blast radius is a design requirement",
        "topic": "Designing for blast-radius isolation",
        "category": "System Design",
        "summary": "A shared cluster, account, or database that hosts every tenant will fail as a unit. Isolation boundaries — accounts, clusters, shards, queues — should match the failure you are willing to explain to customers.",
        "real_world_scenario": "One Kubernetes cluster runs all customers. A noisy neighbor or a bad admission webhook takes the control plane to 100% CPU. Every tenant pages at once, and you cannot restore a single customer without restoring everyone.",
        "technical_explanation": "Blast radius is the set of users or transactions affected by one fault. You shrink it with partitions: AWS accounts, Azure subscriptions, regional cells, shards, worker pools, and bulkheads in code. Shared control planes (one cluster, one RDS, one IAM role) are cheaper until they fail. Decide explicitly which layer is the unit of deploy, the unit of failure, and the unit of restore. Cell-based architecture repeats a full vertical slice so a bad deploy or a regional event cannot eat the whole fleet.",
        "architecture": "Platform account/subscription is separate from workload cells. Each cell has its own compute, data store, and deploy pipeline. A routing layer pins a tenant to a cell. Limits and quotas prevent one cell from consuming shared global resources. Restores are per-cell.",
        "best_practices": [
            "Draw the failure unit before you draw the class diagram.",
            "Avoid super-roles and super-clusters that span all tenants.",
            "Put quotas on shared services so one cell cannot starve others.",
            "Test a cell failure, not only a single-instance failure.",
        ],
        "practical_recommendation": "Write down what fails if your primary database, cluster, or cloud account is gone for two hours. If the answer is 'all customers', split one high-value tenant or one region into a separate cell this quarter.",
        "common_mistakes": [
            "A single shared RDS for every environment and every tenant.",
            "One CI role that can apply every Terraform state.",
            "Calling multi-AZ a multi-tenant isolation strategy.",
        ],
        "what_to_learn_next": [
            "Cell-based architecture.",
            "Bulkheads and queue isolation in application design.",
            "AWS account-per-environment versus account-per-cell.",
        ],
        "tags": ["system-design", "isolation", "cells", "reliability", "tenancy"],
    },
    {
        "title": "At-least-once delivery needs idempotent consumers",
        "topic": "Idempotent consumers in distributed systems",
        "category": "Distributed Systems",
        "summary": "Queues retry. Networks duplicate. If your consumer is not idempotent, every retry is a double charge, a double email, or a corrupted aggregate. Store an idempotency key and treat duplicates as success.",
        "real_world_scenario": "A payment worker times out after charging the card but before deleting the SQS message. The message returns, a second charge occurs, and support spends the afternoon issuing refunds.",
        "technical_explanation": "Producers should send an idempotency key (UUID or natural key) with the message. Consumers persist that key in the same transaction as the side effect, or they use a compare-and-set on a processed-keys table with a TTL. Exactly-once across systems is usually a myth; exactly-once effects are achieved by at-least-once delivery plus idempotent handling. Outbox patterns write the business row and the message in one database transaction, then a publisher relays to the broker. Handlers must be safe under reordering as well as duplication if you have multiple event types.",
        "architecture": "API records an idempotency key. Outbox table in the source DB. Publisher to SQS/Service Bus/Kafka. Consumer checks processed_keys (or a unique constraint on business id) in the same transaction as the write. Poison messages go to a DLQ with an alarm, not an infinite retry.",
        "best_practices": [
            "Give every command an idempotency key from the caller.",
            "Persist 'already processed' in the same transaction as the side effect.",
            "Use a DLQ and an owner; do not retry forever.",
            "Make handlers safe for duplicate and delayed messages.",
        ],
        "practical_recommendation": "Find a consumer that charges, emails, or provisions. Add a unique processed-message table keyed by message id. Replay a duplicate in staging and confirm the side effect happens once.",
        "common_mistakes": [
            "Catching all exceptions and deleting the message anyway.",
            "Using timestamps as idempotency keys.",
            "Assuming a FIFO queue means exactly-once processing.",
        ],
        "what_to_learn_next": [
            "Transactional outbox and inbox patterns.",
            "Kafka exactly-once semantics and their limitations.",
            "Sagas versus two-phase commit.",
        ],
        "tags": ["distributed-systems", "idempotency", "queues", "outbox", "reliability"],
    },
    {
        "title": "Multi-AZ is a lie until you fail over on purpose",
        "topic": "Multi-AZ failover that actually works",
        "category": "High Availability",
        "summary": "Spreading instances across two AZs is not high availability if state, DNS, or a single NAT still lives in one AZ. Fail over in a game day or you will discover the hidden singleton during a real AZ event.",
        "real_world_scenario": "The application is in three AZs. The RDS instance is Multi-AZ. Redis is a single node in az-1. An AZ impairment takes Redis, the app thrashes, and Multi-AZ RDS never gets the chance to matter.",
        "technical_explanation": "AZ independence requires that every synchronous dependency has a story: compute, load balancer, database, cache, NAT, and credentials. Multi-AZ RDS synchronously replicates to a standby; failover time is not zero and connections must retry. Stateless compute should use an autoscaling group or a service with AZ rebalancing. Sticky sessions and in-memory state defeat that. Health checks must fail when a dependency in that AZ is gone, or the load balancer keeps sending traffic into a black hole. Runbooks need connection retry, DNS TTL, and a decision on whether to fail the whole region.",
        "architecture": "ALB across public subnets in three AZs. App tasks in private subnets in three AZs. Multi-AZ database. Clustered cache or a mode that survives node loss. NAT per AZ. Health checks on the real dependency path. Game-day process to stop an AZ with a chaos experiment or a routing change.",
        "best_practices": [
            "List every single-AZ dependency and eliminate or accept it explicitly.",
            "Retry with backoff on database failovers.",
            "Health-check the user journey, not only process liveness.",
            "Rehearse AZ loss at least twice a year.",
        ],
        "practical_recommendation": "Draw the production dependency graph. Circle every component that is not Multi-AZ or actively clustered. Schedule a failover drill for the highest-impact singleton on that list.",
        "common_mistakes": [
            "Calling a single instance in a public subnet Multi-AZ because the VPC has three subnets.",
            "No connection retry, so failover looks like a total outage.",
            "A single NAT gateway in one AZ for the whole VPC.",
        ],
        "what_to_learn_next": [
            "RDS Multi-AZ versus read replicas versus Aurora failover.",
            "AWS Fault Injection Simulator for AZ power-off experiments.",
            "Client-side retry and hedging policies.",
        ],
        "tags": ["ha", "multi-az", "failover", "rds", "reliability"],
    },
    {
        "title": "Backups that were never restored do not exist",
        "topic": "Backup immutability and restore drills",
        "category": "Disaster Recovery",
        "summary": "A backup is a restore you have practiced, with immutability so ransomware cannot delete it. Measure RPO and RTO with a clock, not with a screenshot of a backup job that said success.",
        "real_world_scenario": "Ransomware encrypts production and deletes volume snapshots because the same compromised role could call DeleteSnapshot. The remaining backups are three weeks old because nobody noticed the job IAM error.",
        "technical_explanation": "RPO is how much data you can lose; RTO is how long you can be down. Snapshots, dumps, and cross-region copies each have different RPO. Immutability (S3 Object Lock, Azure immutable blob, AWS Backup Vault Lock) prevents deletion during a retention window even by administrators, with carefully designed break-glass. Restore drills should target a separate account so you do not restore onto production. Checksums and periodic test restores catch silent corruption. Document which systems are not backed up and why.",
        "architecture": "Backups land in a dedicated account or vault with Vault Lock / Object Lock. Replication to a second region for regional disasters. Restore pipeline in an isolated account. Monthly timed restore of a critical datastore. Alarms on backup job failure and on ageing recovery points.",
        "best_practices": [
            "Store backups in an account or vault the workload role cannot delete.",
            "Run a timed restore drill and record actual RTO.",
            "Alert when the newest good restore point exceeds RPO.",
            "Keep restore credentials and runbooks offline from the primary identity plane if that plane is in scope for ransomware.",
        ],
        "practical_recommendation": "Restore last night's production database backup into an isolated account this week. Time it. If you cannot, you do not have a backup; you have a file you have never opened.",
        "common_mistakes": [
            "Same IAM role for workload and snapshot deletion.",
            "Never testing application restore, only VM snapshots.",
            "Declaring RPO of 5 minutes with nightly dumps.",
        ],
        "what_to_learn_next": [
            "AWS Backup Vault Lock and logically air-gapped vaults.",
            "Azure Backup immutability.",
            "Game days that include identity-plane loss.",
        ],
        "tags": ["disaster-recovery", "backups", "rpo", "rto", "immutability"],
    },
    {
        "title": "Automation should not be more privileged than the humans",
        "topic": "Infrastructure automation with least-privilege runners",
        "category": "Infrastructure Automation",
        "summary": "A CI runner with AdministratorAccess is a production admin that logs to a chat channel. Scope automation identities to the stack they own, pin the runner, and treat pipeline changes as privileged reviews.",
        "real_world_scenario": "A self-hosted runner on a developer laptop uses an AWS key with admin. A malicious npm install in a dependabot PR executes on that runner and creates a new IAM user before anyone reviews the PR.",
        "technical_explanation": "Runners execute untrusted code whenever they build pull requests. They need egress controls, no standing cloud admin, and ephemeral environments. GitHub-hosted runners plus OIDC are easier to lock down than perpetual self-hosted VMs. If you must self-host, use ephemeral VMs or Kubernetes jobs that die after one build, with no Docker socket mount. Terraform apply roles should be per-state prefix. Pipeline definitions should be pinned and reviewed like production code. Network paths from runners to production data should not exist.",
        "architecture": "GitHub-hosted or ephemeral self-hosted runners. OIDC to per-stack deploy roles. No Docker socket. No static keys. Production applies require environment reviewers. Runners cannot reach production databases; they can only call cloud APIs they are allowed to. Audit logs for assume-role from CI.",
        "best_practices": [
            "Ephemeral runners; never reuse a long-lived VM for untrusted PRs.",
            "Per-stack cloud roles, not one automation admin.",
            "Disable or tightly restrict pull_request workflows that can assume prod roles.",
            "Pin actions by SHA and review workflow changes.",
        ],
        "practical_recommendation": "Inspect the IAM or Azure role used by CI. If it can create users, disable CloudTrail, or read production data stores, split it into a plan role and an apply role, and remove data-plane read from both.",
        "common_mistakes": [
            "Mounting /var/run/docker.sock into build containers.",
            "Self-hosted runners on persistent VMs with admin credentials.",
            "Allowing Dependabot PRs to run privileged workflows.",
        ],
        "what_to_learn_next": [
            "Ephemeral GitHub runners and Actions OIDC.",
            "Terraform plan in untrusted PRs versus apply in protected environments.",
            "Supply-chain controls for GitHub Actions (SHA pins, immutable releases).",
        ],
        "tags": ["automation", "ci", "least-privilege", "runners", "supply-chain"],
    },
]


def insights_for(topic: str, category: str) -> list[dict]:
    exact = [item for item in INSIGHTS if item["topic"] == topic]
    if exact:
        return exact
    by_category = [item for item in INSIGHTS if item["category"] == category]
    if by_category:
        return by_category
    return list(INSIGHTS)
